### ISSUE TITLE
Remote Tracker state modification (intend: Streaming)

### ISSUE THREAD

**Issue by IngwiePhoenix** [zaxutic/kh2fm-rando-tracker#6]
Hello there!

I am currently trying to setup a stream with a friend of mine. One thing we found out in the process that he, while he is playing the game, can not really update the tracker himself, so it'd be useful to have someone else (i.e. production member) control the tracker remotely.

Since the Co-op mode already utilizes c-s-c solution via WebSockets, would it be possible to create a room with a single instance in which another party could take over the tracking of obtained items?

Thank you in advance! =)

Kind regards, Ingwie

**Comment by zax-xyz** [comment]
Hey Ingwie,

This is incredibly late, and your friend probably doesn't even use this tracker anymore (if he even still streams rando) since everyone uses the auto tracker, but I've implemented this in ac3bd283df85be321f6441b0b3bb1d4b627a3808. There's a single mode to use which is exactly what you asked for, but there's also an OBS remote view option where you can add a browser source directly with true transparency similar to streamlabs overlays. Unfortunately though, I still haven't yet implemented co-op mode (and by extension, the remote view) for important checks mode (this should hopefully be coming soon if I don't procrastinate too much and exams don't keep me too busy).

Thanks again for the feature request, and I apologise this took so long to get around to.
